lzc-sdk-version: 0.1
package: cloud.lazycat.app.netatalk
version: 0.0.7
name: Apple 时间机器备份
description: 
license: https://choosealicense.com/licenses/mit/
homepage: https://github.com/Netatalk/netatalk
author: Netatalk
min_os_version: 1.2.1
locales:
  zh:
    name: "Apple 时间机器备份"
  en:
    name: "Time Machine Server"
  ja:
    name: "タイムマシンサーバー"
application:
  subdomain: netatalk
  routes:
    - /=file:///lzcapp/pkg/content/page
    - /disk.json=exec://8081,/lzcapp/pkg/content/script/backend
  # handlers:
  #   error_page_templates:
  #     '502': /lzcapp/pkg/content/502.html.tpl
  background_task: true
  user_app: false
  ingress:
    - protocol: udp
      port: 548
      service: netatalk
    - protocol: tcp
      port: 548
      service: netatalk
services:
  netatalk:
    # image: registry.lazycat.cloud/u7842111934/netatalk/netatalk:867e0f8860fa7602 # 4.2.3
    # image: registry.lazycat.cloud/u7842111934/netatalk/netatalk:be2628c05e46154d # 4.2.2
    image: registry.lazycat.cloud/u7842111934/netatalk/netatalk:bf35131453c46c76 # 4.2.1
    # image: registry.lazycat.cloud/u7842111934/netatalk/netatalk:bd563185e238c1cb # 4.1.2
    # image: registry.lazycat.cloud/u7842111934/netatalk/netatalk:9111fd7a91682109 # 4.1.1
    # image: registry.lazycat.cloud/u7842111934/netatalk/netatalk3:3.2.10
    # image: registry.lazycat.cloud/app_testing/netatalk/netatalk:c4a3c475209f4af2
    network_mode: host
    environment:
      - "AFP_GROUP=afpusers"
      - "AFP_USER=netatalk"
      - "AFP_PASS=afpadmin"
      - "MANUAL_CONFIG=1"
      - "SERVER_NAME=LazyCat Server"
    binds:
      - /lzcapp/var/afpshare:/mnt/afpshare
      - /lzcapp/var/afpbackup:/mnt/afpbackup
      - /lzcapp/pkg/content/etc/afp.conf:/usr/local/etc/afp.conf
      # - /var/run/dbus:/var/run/dbus
